---
#This playbook deploys the mediawiki 
- name: Media Wiki Database and WebServer
  hosts: all
  become: yes 

# Extra Vars passed from command line
  vars_files: 
    - vault.yml

  roles:
   - mysqldb
   - web
